server:
  port: 8080

spring:
  datasource:
    #    acrs_qa4
    url: jdbc:mysql://124.43.16.185:50301/sp?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Colombo&createDatabaseIfNotExists=true&allowPublicKeyRetrieval=true&useSSL=false
    username: acrs_user
    password: '*pasWord#123*'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
